language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run lint
  - npm run test::unit && codecov
  - npm run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: sky172839465.surge.sh
  project: ./build/
on:
  branch: master